### ISSUE TITLE
Using Maven Central

### ISSUE THREAD

**Issue by grobmeier** [jaredholdcroft/postmark-java#11]
Hi Jared,

I urgently need the lib on Maven Central, as I am starting to use a CI system (CircleCI). 

I would like to know your plans on that. Basically it is very easy to release a component on Maven Central (see: http://central.sonatype.org/pages/ossrh-guide.html) but it requires you to become active and submit a ticket etc first.

It might be a problem as you use com.postmarkapp as namespace, but you are actually working for the company. 

I would like to suggest 2 options:
- you move the lib to your own namespace (like com.jaredholdcroft.postmarkapp) and register com.jaredholdcroft as "your" namespace with Sonatype. Then you are able to push it to Nexus in a breath. Maven, Ivy, Gradle etc users will welcome this.
- if you don't want to put additional effort in this, I will create a wrapper project around your lib. Using the Maven shade plugin, I will rewrap your lib in the de.grobmeier.com.postmarkapp namespace and be finally able to push it to Maven Central.

I think option 1 is to prefer, as you are the maintainer of the code base. If you need support with this task, please let me know. Option 2 would be my workaround. This requires me a few additional steps to do, but well, it would work. Unfortunately I would need to adjust the namespace in my code as well.

Please give me your thoughts on this. 

Thanks!

Christian

**Comment by RupW** [comment]
I think we should switch to the HTTPS endpoint before publishing to maven if that's reasonable? ([my trivial pull request](https://github.com/jaredholdcroft/postmark-java/pull/12))

Another requirement of Maven Central is a documentation .jar. There is a little javadoc there already but it's mostly boilerplate, with the same comment for every class, so possibly OK for a first release.

**Comment by jaredholdcroft** [comment]
Hi, I agree and this needs doing asap.  I'll get on it this week.

**Comment by jitpack** [comment]
Btw, its also easily available on https://jitpack.io/#jaredholdcroft/postmark-java/postmark-java-1.0

**Comment by grobmeier** [comment]
Hello,

in the meantime, I have repackaged it with my domain name and released it to maven. Repackaging was necessary due to Sonatype restrictions. Of course, all the copyright was left intact.

You can use it with'

```
<dependency>
  <groupId>de.grobmeier</groupId>
  <artifactId>postmark4j</artifactId>
  <version>1.1.1</version>
</dependency>
```

I also included @RupW code.

**Comment by jaredholdcroft** [comment]
I've updated and added the source to the Sonatype repo:

```xml
<dependency>
    <groupId>com.jaredholdcroft.java</groupId>
    <artifactId>postmark-java</artifactId>
    <version>1.2</version>
</dependency>
```
