### ISSUE TITLE
Some more docs

### ISSUE THREAD

**Issue by grobmeier** [jaredholdcroft/postmark-java#5]
I just found out you can only send an email via postmark app if your "from" address matches the "from" address in your rack on postmarkapp.com. This is worth to document.

But where? 

My suggestion is to create a maven site or a jekyll based documentation site (jekyll is the machine behind github, so github pages and jekyll is compatible).

Of course, github pages might be another option, or the wiki

**Comment by RupW** [comment]
Would it be OK to take small portions of the Postmark API documentation, e,g. the description of Postmark and the 'Things you should know' section from the developer overview page?

http://developer.postmarkapp.com/

That covers this quite well.

**Comment by jaredholdcroft** [comment]
Project revamp coming soon which will cover this.
